pipeline:
  name: test-minikube-delegate
  identifier: testminikubedelegate
  projectIdentifier: TutorialPei
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.githubpeiwang
        repoName: harness-python
        build: <+input>
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: org.k8sawsminikube
              namespace: test-ns
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: dockerpeiwang
                    image: python:3.10.6-alpine
                    shell: Sh
                    command: echo hello
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: org.k8sawsminikube
              namespace: test-ns
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: dockerpeiwang
                    image: hello-world
                    shell: Sh
                    command: echo test
                  description: test
