pipeline:
  identifier: Build_harness_python_1697414614596
  name: Build harness-python
  orgIdentifier: default
  projectIdentifier: peitest
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1697414062130
        repoName: peiwang-converge/harness-python
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_python_app
                  name: Build Python App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      python -m pip install --upgrade pip
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
